name: portfolio

networks:
  web:
    external: true

services:
  portfolio-backend:
    image: ghcr.io/isaacwallace123/portfolio-backend:latest
    restart: unless-stopped
    networks: [web]
    expose:
      - "8080"
    environment:
      - PORT=8080
    volumes:
      - /mnt/user/appdata/portfolio/backend/config.yaml:/app/config.yaml:ro
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8080/health"]
      interval: 20s
      timeout: 5s
      retries: 6
      start_period: 25s


  portfolio-frontend:
    image: ghcr.io/isaacwallace123/portfolio-frontend:latest
    restart: unless-stopped
    networks: [web]
    expose:
      - "3000"
    environment:
      - BACKEND_URL=http://portfolio-backend:8080
      - PORT=3000
    depends_on:
      - portfolio-backend
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/"]
      interval: 30s
      timeout: 3s
      retries: 5
