version: "3.9"

services:
  docker-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: docker-proxy
    restart: unless-stopped
    environment:
      CONTAINERS: 1
      INFO: 1

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "2375:2375"

  portfolio-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kleff-portfolio-backend
    ports:
      - "8080:8080"
    environment:
      PVE_TOKEN_ID: ${PVE_TOKEN_ID}
      PVE_TOKEN_SECRET: ${PVE_TOKEN_SECRET}
      API_KEY: ${API_KEY:-changeme}
      CONFIG_PATH: /app/config.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config.yaml:/app/config.yaml:ro
    cap_add:
      - NET_RAW
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /run
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/healthz"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 10s
