name: CI (backend & frontend)

on:
  push:
    branches: [ master, main, develop, feature/**, bug/** ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/**'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-build:
    name: Backend build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Go mod download
        run: go mod download

      - name: Build (all packages)
        run: go build ./...

  frontend-build:
    name: Frontend build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: 'frontend/yarn.lock'

      - name: Enable Corepack (Yarn/Pnpm managers)
        run: corepack enable

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Upload dist (if present)
        if: ${{ hashFiles('frontend/dist/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
