name: Build & Push Docker Images

on:
  push:
    branches: [main, master]
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/**"
      - "docker-compose*.yml"
  pull_request:

permissions:
  contents: read
  packages: write

env:
  FRONTEND_IMAGE: ghcr.io/isaacwallace123/portfolio-frontend
  BACKEND_IMAGE: ghcr.io/isaacwallace123/portfolio-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.BACKEND_IMAGE }}:latest
            ${{ env.BACKEND_IMAGE }}:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE }}:latest
            ${{ env.FRONTEND_IMAGE }}:sha-${{ github.sha }}
          build-args: |
            VITE_BACKEND_URL=${{ vars.VITE_BACKEND_URL }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
